# Generated by Django 5.2.7 on 2026-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bug_images/'),
        ),
    ]
